projects:
    app:
        schemaPath: src/graphql/schema.graphql

        extensions:
            endpoints:
                default: http://localhost:4466
    prisma:
        schemaPath: src/core/prisma/generated/prisma-schema.ts
        extensions:
            prisma: ./prisma.yml
