services:
    postgres-db:
        image: postgres:10-alpine
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres

        ports:
            - '5432:5432'
        expose:
            - '5432'
        volumes:
            - postgres-db:/var/lib/postgresql
  mysql-db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'merchant-db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'mysql'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'mysql'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'mysql'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - mysql-db:/var/lib/mysql

# Names our volume
volumes:
    postgres-db:
    mysql-db: