services:
    db:
        image: postgres:10-alpine
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres

        ports:
            - '5432:5432'
        expose:
            - '5432'
        volumes:
            - db:/var/lib/postgresql
# Names our volume
volumes:
    db:
